extends RefCounted

## Purchase cues. Full authored mechanics remain in the explicit unit record.
const COPY: Dictionary[String, String] = {
	"axiom_mentors_reserve": "Gives the Pupil mana and a damage boost.",
	"bastionne_no_pass_writ": "Roots a threat; shields allies behind her.",
	"berebell_unstable": "Lifesteals and punishes wounded enemies.",
	"bo_writ_of_severance": "Charges and knocks up the target.",
	"bonko_bonk": "Stuns; hits stunned targets harder.",
	"brute_slam": "Leaps in and knocks up nearby enemies.",
	"caldera_molten_core": "Charges in and leaves a molten floor.",
	"cinder_fuse_spark": "Burns an area and blocks mana gain inside.",
	"creep_eavesdropping": "Dashes to a wounded foe and spins through enemies.",
	"creep_playable_eavesdropping": "Dives a wounded backliner; spins and chases a kill.",
	"draxelle_colossus_hook": "Hooks the farthest foe into a stunning cleave.",
	"egress_exit_wound": "Executes wounded backliners; retreats on kill.",
	"gable_market_corner": "Marks a foe for ricocheting attacks.",
	"grint_body_check": "Dashes in and knocks an enemy away.",
	"hexeon_prismatic_guillotine": "Executes a wounded backliner; one recast on kill.",
	"ivara_open_bid": "Marks and shreds the healthiest enemy.",
	"juno_vale_constellation_math": "Links unlike allies with mana and a pushing beam.",
	"kett_union_breaker": "Three punches: shred, then shove and stun.",
	"knoll_receipt_mark": "Stuns and shreds both defenses.",
	"korath_absorb_release": "Absorbs damage to heal a wounded ally.",
	"kythera_glyph_bloom": "Grows tougher; recasts heal and strengthen her aura.",
	"kythera_siphon": "Drains magic resistance to share with allies.",
	"luna_moon_beam": "Fires a beam through lined-up enemies.",
	"malachor_debt_of_flesh": "Chains a foe; returns absorbed damage.",
	"mara_arcane_ledger": "A killing blast earns blood once per battle.",
	"marble_sanctuary_bolt": "Shields an ally in its path; slows the farthest foe.",
	"meridian_full_spectrum_treaty": "Allied trait variety powers a prism blast.",
	"miri_lesson_plan": "Shields and launches the Student into a stun.",
	"morrak_reaping_line": "Cleaves a line; executes wounded enemies.",
	"mortem_blood_feast": "Slashes; every third cast cleaves and heals.",
	"noxley_red_static": "Spends Health on blood lightning that heals him.",
	"nullora_last_word": "Delays, then dives to execute a wounded carry.",
	"nyxa_chaos_volley": "Adds arrows to the next four attacks.",
	"omenry_condemning_shot": "Shreds an isolated enemy, then recoils.",
	"orielle_spell_debt": "Delays a blast; leaves a damaging mana-tax zone.",
	"paisley_bubbles": "Shields two weak allies; bubbles pop into stuns.",
	"pilfer_pocket_swap": "Swaps with and disarms the farthest enemy.",
	"prisma_color_theory": "Prism field damages once and blocks mana inside.",
	"quillith_final_exam": "Makes the Pupil repeat its ability at reduced power.",
	"quorra_timeplate_lunge": "Blinks deep; rewinds if her wound completes.",
	"ravel_puppet_strings": "Links allies with a string that yanks enemies away.",
	"repo_writ_of_severance": "Temporarily steals both defenses from an enemy.",
	"rooket_brace_shot": "Braces, then pierces and shreds a firing line.",
	"sable_footnote_piercer": "Pierces and shreds; hitting two refunds mana.",
	"saffron_golden_poultice": "Heals a threatened ally; overheal becomes a shield.",
	"sari_default": "Marks a foe; the next three attacks shred Armor.",
	"teller_margin_call": "Fires two long shots; kills can earn blood.",
	"totem_cleanse": "Cleanses and shields the allied carry.",
	"velour_silk_knot": "Roots a threat while healing a wounded ally.",
	"vesper_late_fee": "Delays an execution dive; retreats only on kill.",
	"veyra_harden": "Protects nearby allies from damage and control.",
	"volt_arc_lock": "Cages one enemy in damaging, stunning lightning.",
	"vykos_blood_feast": "Cleaves a cone and heals from damage dealt.",
}

static func copy_for(ability_id: String, fallback_name: String) -> String:
	return String(COPY.get(ability_id, fallback_name))
